import React, { useState } from "react";
import "./ServicesTab.css";
import { Pill, ShieldAlert, Activity, MessageCircle } from 'lucide-react';

const services = [
  {
    id: "info",
    title: "Drug Information & Clarity",
    icon: <Pill size={32} />,
    description: "Plain-language summaries of medications.",
    detail:
      "Search a medication (or a set of symptoms) and get a plain-language answer covering what it is, how it works, its main uses, common side effects, and warnings. Results are generated by an AI model for education only - confirm anything that matters with your doctor or pharmacist.",
  },
  {
    id: "safety",
    title: "Safety & Alert Systems",
    icon: <ShieldAlert size={32} />,
    description: "Warnings, precautions, and emergency warning signs.",
    detail:
      "Every answer includes a warnings section with contraindications and precautions, plus an emergency-warning line describing signs that mean you should seek immediate medical attention. Queries that mention emergency symptoms (chest pain, difficulty breathing, and similar) skip the AI call entirely and direct you to emergency services instead.",
  },
  {
    id: "tracking",
    title: "Comprehensive Safety Guardrails",
    icon: <Activity size={32} />,
    description: "How side effects, contraindications, and dosage limits are explained.",
    detail:
      "Answers separate common side effects from serious adverse reactions, call out who should avoid the medication (for example, people with pre-existing kidney or liver conditions), and state dosage limits. This is general, AI-assisted guidance: CuraLink does not track your doses or log side effects for you.",
  },
  {
    id: "legal",
    title: "Legal & Ethical Integrity",
    icon: <MessageCircle size={32} />,
    description: "A fixed medical disclaimer, no ads, no medication sales.",
    detail:
      "CuraLink is educational, not a diagnosis. Every answer carries the same disclaimer stating it is not a substitute for professional medical advice, and results contain no pharmaceutical advertising, sponsored ranking, or medication sales.",
  },
];

function ServicesTab() {
  const [activeService, setActiveService] = useState(services[0].id);

  return (
    <section className="servicesContainer">
      <div className="servicesHeader">
        <h2>Our Services</h2>
        <p>Explore what CuraLink does today - AI-assisted medication information, clearly explained.</p>
      </div>

      <div className="servicesGrid">
        {services.map((service) => (
          <div
            key={service.id}
            className={`serviceCard ${activeService === service.id ? "active" : ""}`}
            onClick={() => setActiveService(service.id)}
          >
            <div className="cardIcon">{service.icon}</div>
            <h3 className="cardTitle">{service.title}</h3>
            <p className="cardDescription">{service.description}</p>
          </div>
        ))}
      </div>

      {/* Active Service Details - one distinct block per selected service */}
      <div className="serviceDetails">
        {services
          .filter((s) => s.id === activeService)
          .map((service) => (
            <div key={service.id}>
              <h3>{service.title}</h3>
              <p>{service.detail}</p>
            </div>
          ))}
      </div>
    </section>
  );
}

export default ServicesTab;

