import mongoose from 'mongoose';

// Shared, cross-user cache of AI answers.
//
// Keyed by `normalizedQuery` ONLY - deliberately no userId. The cached value is
// a model answer to a public medical question, not anything personal, so one
// entry can serve every user; that is also what stops the same identical query
// from paying for a second Groq call.
//
// Entries are disposable: the TTL index on createdAt makes MongoDB delete them
// 30 days after they were written, so an answer generated by an old model/prompt
// cannot sit in the cache forever.
//
// NOTE: the legacy `searches` collection (see ./Search.js, kept read-only for
// the migration script) still holds the old combined cache+history rows and
// needs a one-time migration into SearchCache + SearchHistory.
const searchCacheSchema = new mongoose.Schema({
  // trim + lowercase of the incoming query - the exact value the controller
  // derives from req.body.query, so lookups and upserts always agree.
  normalizedQuery: {
    type: String,
    required: true,
    // unique doubles as the index and as the guarantee that two concurrent
    // upserts can never create two rows for the same query.
    unique: true,
  },
  response: {
    type: mongoose.Schema.Types.Mixed,
    required: true,
  },
  // Model version that produced `response` (e.g. 'llama-3.3-70b-versatile'),
  // so the cache can be qualified or flushed when the model/prompt changes.
  modelVersion: {
    type: String,
    required: true,
  },
  createdAt: {
    type: Date,
    default: Date.now,
    // TTL index -> document is removed 30 days after createdAt.
    expires: 30 * 24 * 60 * 60,
  },
});

const SearchCache = mongoose.model('SearchCache', searchCacheSchema);

export default SearchCache;
