import Groq from 'groq-sdk';
import mongoose from 'mongoose';
import SearchCache from '../models/SearchCache.js';
import SearchHistory from '../models/SearchHistory.js';
import { MEDICAL_SYSTEM_PROMPT } from '../config/medicalPrompt.js';

// Kept in one place so it can be written onto every cache row; a cache entry
// generated by a different model version can be recognized (and flushed).
const MODEL_VERSION = 'llama-3.3-70b-versatile';

// The single normalization step for a query: trim + lowercase. It defines the
// cache key, so it must stay identical to what SearchCache.normalizedQuery holds.
const normalizeQuery = (query) => query.trim().toLowerCase();

// History write is best-effort: a failed insert must never turn a successful
// search into a 500. Scoped to the requesting user, never shared.
const recordHistory = async (userId, query, response) => {
  try {
    await SearchHistory.create({ userId, query, response });
  } catch (error) {
    console.error('Search history write error:', error?.message || error);
  }
};

export const medicalSearch = async (req, res) => {
  try {
    const { query } = req.body;
    const normalizedQuery = normalizeQuery(query);

    // 1. Shared cache lookup - keyed by the query alone, no userId: the answer
    //    itself is not personal, so a hit here is free for every user.
    const cachedSearch = await SearchCache.findOne({ normalizedQuery });
    if (cachedSearch) {
      // Still logged to *this* user's history so their own search shows up in
      // their history even when someone else warmed the cache first.
      await recordHistory(req.user.id, normalizedQuery, cachedSearch.response);
      return res.status(200).json({ source: 'cache', data: cachedSearch.response });
    }

    // 2. Cache miss -> exactly one upstream call for this query.
    const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

    const completion = await groq.chat.completions.create({
      model: MODEL_VERSION,
      messages: [
        { role: 'system', content: MEDICAL_SYSTEM_PROMPT },
        { role: 'user', content: `User searched for: "${query}"` }
      ],
      response_format: { type: 'json_object' }
    });

    // Parse JSON
    let parsedResponse;
    try {
      parsedResponse = JSON.parse(completion.choices[0].message.content);
    } catch (parseError) {
      console.error('JSON parse error. Raw response:', completion.choices[0].message.content);
      return res.status(500).json({ message: 'Error parsing response from AI model', raw: completion.choices[0].message.content });
    }

    // 3. Atomic upsert instead of a plain save: the unique index on
    //    normalizedQuery plus upsert means concurrent misses for the same query
    //    collapse into a single row and never race into a duplicate-key error.
    await SearchCache.findOneAndUpdate(
      { normalizedQuery },
      {
        $setOnInsert: {
          normalizedQuery,
          response: parsedResponse,
          modelVersion: MODEL_VERSION,
          createdAt: new Date(),
        },
      },
      { upsert: true }
    );

    // 4. Separately: a per-user history row for the user who asked.
    await recordHistory(req.user.id, normalizedQuery, parsedResponse);

    return res.status(200).json({ source: 'ai', data: parsedResponse });

  } catch (error) {
    console.error('Error in medicalSearch:', error?.message || error);
    return res.status(500).json({ message: error?.message || 'Server error during search' });
  }
};

// GET /api/search/history - the latest 20 entries for this user only.
// Only query/response/createdAt (+_id, which the DELETE route needs) leave the
// DB: no userId, no __v, no other internals. .lean() skips hydrating documents.
export const getSearchHistory = async (req, res) => {
  try {
    const history = await SearchHistory.find({ userId: req.user.id })
      .select('_id query response createdAt')
      .sort({ createdAt: -1 })
      .limit(20)
      .lean();

    return res.status(200).json(history);
  } catch (error) {
    console.error('Error fetching search history:', error);
    return res.status(500).json({ message: 'Server error fetching history' });
  }
};

// GET /api/search/history/export - every record for this user, as JSON.
export const exportHistory = async (req, res) => {
  try {
    const records = await SearchHistory.find({ userId: req.user.id })
      .select('_id query response createdAt')
      .sort({ createdAt: -1 })
      .lean();

    return res.status(200).json(records);
  } catch (error) {
    console.error('Error exporting search history:', error);
    return res.status(500).json({ message: 'Server error exporting search history' });
  }
};

// DELETE /api/search/history/:id - one entry, only if it is the caller's.
export const deleteHistoryItem = async (req, res) => {
  try {
    const { id } = req.params;

    // A non-ObjectId simply cannot exist, so it is a miss either way; answering
    // 404 avoids a mongoose CastError (and avoids probing id formats).
    if (!mongoose.isValidObjectId(id)) {
      return res.status(404).json({ message: 'Search history entry not found' });
    }

    // Ownership is enforced inside the filter itself: another user's document
    // is invisible to this query and therefore undeletable by this caller.
    const result = await SearchHistory.deleteOne({ _id: id, userId: req.user.id });

    if (result.deletedCount === 0) {
      return res.status(404).json({ message: 'Search history entry not found' });
    }

    return res.json({ message: 'Search history entry deleted' });
  } catch (error) {
    console.error('Error deleting search history entry:', error);
    return res.status(500).json({ message: 'Server error deleting history entry' });
  }
};

// DELETE /api/search/history - wipe every entry of the calling user only.
export const clearHistory = async (req, res) => {
  try {
    const result = await SearchHistory.deleteMany({ userId: req.user.id });

    return res.json({
      message: 'Search history cleared',
      deletedCount: result.deletedCount,
    });
  } catch (error) {
    console.error('Error clearing search history:', error);
    return res.status(500).json({ message: 'Server error clearing history' });
  }
};
