import Groq from 'groq-sdk';
import mongoose from 'mongoose';
import SearchCache from '../models/SearchCache.js';
import SearchHistory from '../models/SearchHistory.js';
import {
  MEDICAL_SYSTEM_PROMPT,
  STRICT_FORMAT_INSTRUCTION,
  EMERGENCY_KEYWORDS,
  EMERGENCY_RESPONSE,
} from '../config/medicalPrompt.js';
import { aiResponseSchema } from '../validation/schemas.js';

// Kept in one place so it can be written onto every cache row; a cache entry
// generated by a different model version can be recognized (and flushed).
const MODEL_VERSION = 'openai/gpt-oss-120b';

// --- Timeouts -------------------------------------------------------------
// Every Groq attempt is aborted after at most GROQ_TIMEOUT_MS (12s, inside the
// required 10-15s window). The whole handler is capped at REQUEST_BUDGET_MS so
// we always finish before Vercel's maxDuration (15s, vercel.json) kills the
// invocation - RESPONSE_BUFFER_MS of that budget is reserved for parsing,
// the cache/history writes and serializing the response.
const GROQ_TIMEOUT_MS = 12_000;
const RESPONSE_BUFFER_MS = 2_000;
const REQUEST_BUDGET_MS = 14_000;

// First call plus exactly one stricter retry when the shape is wrong.
const MAX_ATTEMPTS = 2;

// Client-facing messages: generic on purpose - neither the raw model output nor
// the raw provider/SDK error may reach a caller.
const BAD_GATEWAY_MESSAGE = 'The search service returned an unexpected response. Please try again.';
const TIMEOUT_MESSAGE = 'The search took too long to respond. Please try again.';

// The single normalization step for a query: trim + lowercase. It defines the
// cache key, so it must stay identical to what SearchCache.normalizedQuery holds.
const normalizeQuery = (query) => query.trim().toLowerCase();

// Substring match on the normalized query. Runs before the cache and before
// Groq, so a query we are about to redirect never costs an API call.
const matchEmergencyKeyword = (normalizedQuery) =>
  EMERGENCY_KEYWORDS.find((keyword) => normalizedQuery.includes(keyword));

// Our AbortSignal.timeout() fires; groq-sdk then sees signal.aborted and throws
// APIUserAbortError. Note that error keeps name === 'Error' (message "Request
// was aborted."), so it MUST be matched by instanceof - the name checks below
// only cover the unwrapped variants (DOMException 'TimeoutError'/'AbortError')
// and the SDK's own connection timeout. All of them mean "our timeout", i.e. a
// clean 504, never a generic 500.
const isTimeoutError = (error) =>
  error instanceof Groq.APIUserAbortError ||
  error?.name === 'TimeoutError' ||
  error?.name === 'AbortError' ||
  error?.name === 'APIConnectionTimeoutError' ||
  error?.cause?.name === 'TimeoutError' ||
  error?.cause?.name === 'AbortError';

const buildMessages = (query, { strict }) => [
  {
    role: 'system',
    content: strict
      ? `${MEDICAL_SYSTEM_PROMPT}\n${STRICT_FORMAT_INSTRUCTION}`
      : MEDICAL_SYSTEM_PROMPT,
  },
  { role: 'user', content: `User searched for: "${query}"` },
];

// One Groq round-trip with a hard AbortSignal timeout.
const requestCompletion = (query, { strict, timeoutMs }) => {
  const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });
  return groq.chat.completions.create(
    {
      model: MODEL_VERSION,
      messages: buildMessages(query, { strict }),
      response_format: { type: 'json_object' },
    },
    { signal: AbortSignal.timeout(timeoutMs) }
  );
};

// Reads the assistant's JSON string out of the provider response without ever
// indexing blindly: returns null for a malformed payload (missing/empty
// choices, missing or empty content) so the caller can answer cleanly.
const extractContent = (completion) => {
  if (!completion || !Array.isArray(completion.choices) || completion.choices.length === 0) {
    return null;
  }
  const content = completion.choices[0]?.message?.content;
  return typeof content === 'string' && content.trim() ? content : null;
};

// Fail fast at boot if the static emergency payload ever drifts away from the
// schema the frontend needs (it must always be renderable and always carry the
// disclaimer).
const emergencyCheck = aiResponseSchema.safeParse(EMERGENCY_RESPONSE);
if (!emergencyCheck.success) {
  throw new Error(
    `EMERGENCY_RESPONSE does not match aiResponseSchema: ${JSON.stringify(emergencyCheck.error.issues)}`
  );
}

// History write is best-effort: a failed insert must never turn a successful
// search into a 500. Scoped to the requesting user, never shared.
const recordHistory = async (userId, query, response) => {
  try {
    await SearchHistory.create({ userId, query, response });
  } catch (error) {
    console.error('Search history write error:', error?.message || error);
  }
};

export const medicalSearch = async (req, res) => {
  try {
    const { query } = req.body;
    const normalizedQuery = normalizeQuery(query);

    // 1. Emergency gate - FIRST, before cache and before Groq: we never spend
    //    an API call (or a stale cached answer) on a query we redirect anyway.
    if (matchEmergencyKeyword(normalizedQuery)) {
      console.warn('Emergency keyword matched - redirecting without an AI call', {
        requestId: req.id,
      });
      await recordHistory(req.user.id, normalizedQuery, EMERGENCY_RESPONSE);
      return res.status(200).json({ source: 'emergency', data: EMERGENCY_RESPONSE });
    }

    // 2. Shared cache lookup - keyed by the query alone, no userId: the answer
    //    itself is not personal, so a hit here is free for every user.
    const cachedSearch = await SearchCache.findOne({ normalizedQuery });
    if (cachedSearch) {
      const cached = aiResponseSchema.safeParse(cachedSearch.response);
      if (cached.success) {
        // Still logged to *this* user's history so their own search shows up
        // in their history even when someone else warmed the cache first.
        await recordHistory(req.user.id, normalizedQuery, cached.data);
        return res.status(200).json({ source: 'cache', data: cached.data });
      }
      // Rows written before this schema existed (or by older code) must never
      // reach the frontend: treat them as a miss and regenerate.
      console.warn('Cached response failed validation - regenerating', {
        requestId: req.id,
        issues: cached.error.issues.map((issue) => issue.path.join('.')),
      });
    }

    // 3. Groq: one call, plus exactly one stricter retry if the shape is wrong.
    const deadlineAt = Date.now() + REQUEST_BUDGET_MS;
    let parsedResponse = null;

    for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt += 1) {
      const timeoutMs = Math.min(
        GROQ_TIMEOUT_MS,
        deadlineAt - Date.now() - RESPONSE_BUFFER_MS
      );
      if (timeoutMs <= 0) {
        return res.status(504).json({ message: TIMEOUT_MESSAGE });
      }

      let completion;
      try {
        completion = await requestCompletion(query, { strict: attempt > 1, timeoutMs });
      } catch (error) {
        if (isTimeoutError(error)) {
          // Clean timeout answer - not a generic 500, and no SDK internals.
          console.warn('Groq request timed out', { requestId: req.id, attempt, timeoutMs });
          return res.status(504).json({ message: TIMEOUT_MESSAGE });
        }
        // Real provider/network failures keep their existing handling below.
        throw error;
      }

      const content = extractContent(completion);
      if (content === null) {
        // Malformed provider response (no/empty choices or content).
        console.error('Groq returned a malformed completion', {
          requestId: req.id,
          attempt,
          topKeys: Object.keys(completion ?? {}),
          choiceCount: Array.isArray(completion?.choices) ? completion.choices.length : 'not-an-array',
        });
        return res.status(502).json({ message: BAD_GATEWAY_MESSAGE });
      }

      let candidate = null;
      try {
        candidate = JSON.parse(content);
      } catch {
        // Not JSON at all -> counts as a shape failure, handled below.
      }

      const validated = candidate === null ? null : aiResponseSchema.safeParse(candidate);
      if (validated?.success) {
        parsedResponse = validated.data;
        break;
      }

      console.warn('AI response failed validation', {
        requestId: req.id,
        attempt,
        notJson: candidate === null,
        issues: validated ? validated.error.issues.map((issue) => issue.path.join('.')) : [],
      });

      if (attempt === MAX_ATTEMPTS) {
        // Second failure: generic 502, never the raw model output.
        return res.status(502).json({ message: BAD_GATEWAY_MESSAGE });
      }
      // Otherwise loop once more with STRICT_FORMAT_INSTRUCTION appended.
    }

    if (!parsedResponse) {
      return res.status(502).json({ message: BAD_GATEWAY_MESSAGE });
    }

    // 4. Atomic upsert instead of a plain save: the unique index on
    //    normalizedQuery plus upsert means concurrent misses for the same query
    //    collapse into a single row and never race into a duplicate-key error.
    await SearchCache.findOneAndUpdate(
      { normalizedQuery },
      {
        $setOnInsert: {
          normalizedQuery,
          response: parsedResponse,
          modelVersion: MODEL_VERSION,
          createdAt: new Date(),
        },
      },
      { upsert: true }
    );

    // 5. Separately: a per-user history row for the user who asked.
    await recordHistory(req.user.id, normalizedQuery, parsedResponse);

    return res.status(200).json({ source: 'ai', data: parsedResponse });

  } catch (error) {
    console.error('Error in medicalSearch:', error?.message || error);
    return res.status(500).json({ message: error?.message || 'Server error during search' });
  }
};

// GET /api/search/history - the latest 20 entries for this user only.
// Only query/response/createdAt (+_id, which the DELETE route needs) leave the
// DB: no userId, no __v, no other internals. .lean() skips hydrating documents.
export const getSearchHistory = async (req, res) => {
  try {
    const history = await SearchHistory.find({ userId: req.user.id })
      .select('_id query response createdAt')
      .sort({ createdAt: -1 })
      .limit(20)
      .lean();

    return res.status(200).json(history);
  } catch (error) {
    console.error('Error fetching search history:', error);
    return res.status(500).json({ message: 'Server error fetching history' });
  }
};

// GET /api/search/history/export - every record for this user, as JSON.
export const exportHistory = async (req, res) => {
  try {
    const records = await SearchHistory.find({ userId: req.user.id })
      .select('_id query response createdAt')
      .sort({ createdAt: -1 })
      .lean();

    return res.status(200).json(records);
  } catch (error) {
    console.error('Error exporting search history:', error);
    return res.status(500).json({ message: 'Server error exporting search history' });
  }
};

// DELETE /api/search/history/:id - one entry, only if it is the caller's.
export const deleteHistoryItem = async (req, res) => {
  try {
    const { id } = req.params;

    // A non-ObjectId simply cannot exist, so it is a miss either way; answering
    // 404 avoids a mongoose CastError (and avoids probing id formats).
    if (!mongoose.isValidObjectId(id)) {
      return res.status(404).json({ message: 'Search history entry not found' });
    }

    // Ownership is enforced inside the filter itself: another user's document
    // is invisible to this query and therefore undeletable by this caller.
    const result = await SearchHistory.deleteOne({ _id: id, userId: req.user.id });

    if (result.deletedCount === 0) {
      return res.status(404).json({ message: 'Search history entry not found' });
    }

    return res.json({ message: 'Search history entry deleted' });
  } catch (error) {
    console.error('Error deleting search history entry:', error);
    return res.status(500).json({ message: 'Server error deleting history entry' });
  }
};

// DELETE /api/search/history - wipe every entry of the calling user only.
export const clearHistory = async (req, res) => {
  try {
    const result = await SearchHistory.deleteMany({ userId: req.user.id });

    return res.json({
      message: 'Search history cleared',
      deletedCount: result.deletedCount,
    });
  } catch (error) {
    console.error('Error clearing search history:', error);
    return res.status(500).json({ message: 'Server error clearing history' });
  }
};
